[[plugins]] # Plugin to easily access Most Recently Used (MRU) files
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
on_path = '.*'

[[plugins]] # Yank
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'
on_event = 'TextYankPost'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_source = 'denite.nvim'
on_path = '.*'
depends = ['neomru.vim']
hook_add = '''
nmap <silent> <C-u><C-l> :<C-u>Denite file_mru<CR>
nmap <silent> <C-u><C-p> :<C-u>Denite file_rec<CR>

'''
